project:
  type: website
  preview:
    port: 4200

website:
  title: "Item Response Warehouse"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: standard.qmd
        text: Data Standard
      - href: data.qmd
        text: Data
      - href: docs.qmd
        text: Documentation
      - href: analysis.qmd
        text: Analysis
      - href: research.qmd
        text: Research
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact Us


format:
  html:
    theme:
      - cosmo
      - scss/global.scss
    toc: false
    grid:
      sidebar-width: 0px
      body-width: 1200px
      margin-width: 0px
    callout-icon: false
    df-print: kable
    code-fold: true


execute: 
  echo: false
  message: false
  warning: false
  error: false
